apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend-dev-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-backend-dev-pod
    template:
      metadata:
        labels:
          app: todo-backend-dev-pod
      spec:
        containers:
          - name: todo-backend-dev-cont
            image: 1md3nd/todo-backend-dev:latest
            ports:
              - containerPort: 3001
            resources:
              requests:
                memory: "256Mi"
              limits:
                memory: "512Mi"
            livenessProbe:
              httpGet:
                path: /
                port: 3001
              initialDelaySeconds: 5
              periodSeconds: 10
            readnessProbe:
              httpGet:
                path: /
                port: 30001
              initialDelaySeconds: 5
              periodSeconds: 10
            env:
            - name: RDS_HOSTNAME
            