apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend-dev-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-backend-dev-pod
  template:
    metadata:
      labels:
        app: todo-backend-dev-pod
    spec:
      initContainers:
      - name: init-db-check
        image: busybox
        command: ['sh', '-c', 'until nc -z -v -w30 todo-database-dev-service 3306; do echo "Waiting for database..."; sleep 5; done; echo "Database is up"']
      containers:
      - name: todo-backend-dev-cont
        image: 1md3nd/todo-backend-dev:latest
        ports:
          - containerPort: 3001
        resources:
          requests:
            memory: "256Mi"
          limits:
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /api
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 10
        env:
          - name: DB_HOSTNAME
            value: todo-database-dev-service
          - name: DB_USERNAME
            value: root
          - name: DB_PASSWORD
            value: abcde
          - name: PORT
            value: '3306'
          - name: DATABASE
            value: test
