apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-database-dev-deployment
spec:
  selector:
    matchLabels:
      app: todo-database-dev
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: todo-database-dev
    spec:
      containers:
      - image: mysql:latest
        name: todo-database-dev-cont
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: abcde
        - name: MYSQL_DATABASE
          value: test
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: todo-database-dev-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  selector:
    app: todo-database-dev