apiVersion: v1
kind: Service
metadata:
  name: todo-backend-dev-service
spec:
  type: NodePort
  selector:
    app: todo-backend-dev-pod
  ports:
    - port: 3001
      targetPort: 3001
      nodePort: 30001